# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# NV-pairs voor dit project
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
toolbox: "/Users/nipper/r_projects/salsa_toolbox_r/src/salsa_toolbox.R"
# nip_xpr_gd_reg: "Nipper Express 0.2.FoSa"
cz_modelrooster_gd_reg: "Roosters 3.0"

# host: "logmac"
# host: "uitzendmac"

# home_radiologik.uitzendmac: "//UITZENDMAC-CZ/Radiologik--preview/"

home_radiologik.logmac: "//LOGMAC/Radiologik/"
home_radiologik.uitzendmac: "//UITZENDMAC-CZ/Radiologik/"

home_schedulerswitch.logmac: "//LOGMAC/tech/Documents/Salsa/nipper_ctl/"
home_schedulerswitch.uitzendmac: "//UITZENDMAC-CZ/tech/Documents/Salsa/nipper_ctl/"
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}

cz_modelrooster_versie: "20190801"

cur_cz_week: "2019-10-10 13:00"
