---
output: pdf_document
title: "Weekschema iTunes-playlists"
date: '`r dtm <- lubridate::today(); format(dtm, format = "%e %B %Y")`'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r schema, echo=FALSE}
suppressMessages(library(knitr))
suppressMessages(library(magrittr))
suppressMessages(library(dplyr))
suppressMessages(library(stringr))
suppressMessages(library(kableExtra))

options(knitr.table.format = "latex")

plw <- readRDS("plw.RDS")
plw %<>% rename(audio = sys_audiotitel)

plw_mac <- plw %>% group_by(mac) %>% summarise(n = n())

plw_hijack <- readRDS("plw_hijack.RDS") 
plw_hijack %<>% rename(audio = sys_audiotitel)
plw_hijack$audio <- str_sub(plw_hijack$audio, 9)

plw_hijack_mac <- plw_hijack %>% group_by(mac) %>% summarise(n = n())

kable(plw_hijack, booktabs = T, longtable = T, # linesep = "",
      caption = "HiJack Files") %>%
  kable_styling(latex_options = c("striped", "HOLD_position", "repeat_header"), font_size = 8, position = "left") %>% 
  group_rows(index = c("Lognac" = 1, "Uitzendmac" = 10))

kable(plw, booktabs = T, longtable = T, # linesep = "",
      caption = "Regular Files") %>%
  kable_styling(latex_options = c("striped", "HOLD_position", "repeat_header"), font_size = 8, position = "left") %>% 
  group_rows(index = c("Lognac" = 4, "Uitzendmac" = 78))
```
